# Generated by Django 4.0.1 on 2022-03-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_image_imo'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Type',
            field=models.CharField(choices=[('pp', 'product'), ('ss', 'service')], default=None, max_length=2),
        ),
    ]
