# Generated by Django 4.0.1 on 2022-03-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_image_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
