# Generated by Django 4.0.1 on 2022-03-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_image_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='desc',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
