# Generated by Django 4.0.1 on 2022-04-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_image_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('approved', models.BooleanField(default=False)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=120)),
                ('items', models.CharField(max_length=4000)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('zip_code', models.IntegerField(default='')),
            ],
        ),
    ]
