# Generated by Django 4.0.1 on 2022-04-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_orders_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imo',
            field=models.ImageField(default=True, upload_to='images'),
        ),
    ]
