# Generated by Django 4.0.1 on 2022-04-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_image_imo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Type',
            field=models.CharField(choices=[('pp', 'product'), ('ss', 'service')], default=None, max_length=2, null=True),
        ),
    ]
