# Generated by Django 4.0.1 on 2022-05-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_image_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_office', models.CharField(max_length=50)),
                ('current_stateandcity', models.CharField(max_length=50)),
            ],
        ),
    ]
