# Generated by Django 4.0.1 on 2022-05-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_tracker_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='username',
        ),
    ]
