# Generated by Django 4.0.1 on 2022-05-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_tracker_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
