# Generated by Django 4.1.2 on 2022-10-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_orders_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
