# Generated by Django 4.1.2 on 2022-10-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_remove_orders_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.CharField(default='118', max_length=555),
        ),
    ]
