# Generated by Django 4.1.2 on 2022-10-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_orders_order_id_alter_orders_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.CharField(default=None, max_length=555),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='899', max_length=120),
        ),
    ]
