# Generated by Django 4.0.1 on 2022-11-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_orders_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.CharField(max_length=550),
        ),
    ]
