# Generated by Django 4.0.1 on 2022-12-22 07:48

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_orders_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=django_mysql.models.ListCharField(models.CharField(max_length=550), max_length=300, size=None),
        ),
    ]
