# Generated by Django 4.0.1 on 2022-12-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_alter_orders_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.CharField(default='anonymous', max_length=40),
        ),
    ]
